# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15OEHsDo6h-ESdsYLPbTlAUsA2y5C3lnz
"""

from os import name
import numpy as np

def newton(x0,f,grad,H,tol=1e-6):
    
    x = np.array(x0)

    list_x = [x]
    list_fx = [f(x)]

    while np.linalg.norm(grad(x)) > tol:
        
        hinv = np.linalg.inv(H(x))
        g = np.array([grad(x)]).T
        delta = np.matmul(hinv,g)
        x = x - delta.T
        x = x[0]
        
        list_x.append(x)
        list_fx.append(f(x))

        g = grad(x)

    return x,f(x),list_x,list_fx

f = lambda x: (100*(x[1] - x[0]**2)**2 + (x[0]-1)**2) 
    grad = lambda x: [-400*(x[1]-x[0]**2)*x[0] + 2*(x[0]-1), 200*(x[1]-x[0]**2)]
    H = lambda x: [[-400*x[1]+1200*x[0]**2,-400*x[0]],[-400*x[0],200]]

    xs,fs,xlist,fx_list = newton([1,-2],f,grad,H)

    print(xs)
    print(xlist)